server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testluchen?serverTimezone=UTC
    username: root
    password: love6739176.
    driver-class-name: com.mysql.cj.jdbc.Driver
    #最大等待连接数量  设置为0没有限制
    #schema:     -  classpath:department.sql
    #initialization-mode: always
    tomcat:
      max-idle: 10
      #最大活跃连接数
      max-active: 50
      #最大等待毫秒数
      max-wait: 10000
      #数据库连接池初始化连接数
      initial-size: 5
  redis:
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 127.0.0.1
    password: ""
    timeout: 1000
  cache:
    type: redis
    cache-names: redisCache
  servlet:
    multipart:
      location: d:/springboot
      max-file-size: 5242880
      max-request-size: 20MB
  mvc:
    locale-resolver: accept_header
    static-path-pattern:  /static/**
  messages:
    encoding: UTF-8
    basename: international
    cache-duration: 3600
  security:
    user:
      name: luchen
      password: 123456
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    #是否启用连接池
    pool:
      enabled: true
      #连接池子的最大连接数
      max-connections: 50
    packages:
      trusted: com.aynu.redis.pojo,java.lang
  jms:
    #是否适用发布订阅模式 默认是false 使用的是点对点模式
    pub-sub-domain: true
    #默认的目的地址
    template:
      default-destination: activemq.default.destination

  #rabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #是否确认发送的对象被消费
    publisher-confirms: true
    #RabbitMq的消息队列名称 由他发送字符串

#rabbitmq:
#  queue:
#    msg: spring-boot-queue-msg
#    user: spring-boot-queue-message

mybatis:
  type-handlers-package: com.aynu.redis.typehandler
